package app;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;

public class generarPrograma {
	
	public void generarPrograma1() {
        String str = "", h = "";
        String t = "";

        try {

            FileOutputStream fos = new FileOutputStream("agenda.html");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            //graba los datos de la lista
           
            h = "<!DOCTYPE html>"
            	+ "<html lang="+"\""+"en"+"\""+">"
                    + "<head>"
	            		+ "<meta charset="+ "\"" +"UTF-8"+ "\"" +">"
	                    + "<meta name="+ "\"" +"viewport"+ "\"" +" content="+ "\"" +"width=device-width, initial-scale=1.0"+ "\"" +">"
	                    + "<meta http-equiv="+ "\"" +"X-UA-Compatible"+ "\"" +" content="+ "\"" +"ie=edge"+ "\"" +">"
	                    + "<title>Agenda</title>"
                    + " < / head >"
                    
                    + "<body bgcolor="+ "\"" +"orange>"+ "\"" +"[br /]"
	                    + "<center> < TABLE BORDER ="+ "\"" +" 2"+ "\"" +" bgcolor ="+ "\"" +" gray"+ "\"" +" >" 
	                    + "<TR><TD>obras de teatro</TD></TR></TABLE></center>[br /]"
	                    + "<TABLE BORDER="+ "\"" +"1"+ "\"" +" bgcolor="+ "\"" +"gray "+ "\"" +"><TR><TD>[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >[br /]"
	                    + "<TR><TD>[br /]"                    
	                    + "<a name=" + "\"" + "El Sueno de una Noche de Verano" + "\"" + ">[/url]"
	                    + "<p>El Sueno de una Noche de Verano"
	                    + "Esta comedia en cinco actos en verso y prosa de William Shakespeare fue escrita alrededor de 1595 y representada hacia la misma epoca;"
	                    + " se publico in-quarto en 1600 y en 1619, e in-folio el ano 1623. , pero pudo tomarla de Chaucer o Plutarco."
	                    + "precio=$100</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (1).gif" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Lluvia constante" + "\"" + ">[/url]"
	                    + "<p>Lluvia constante"
	                    + "Los artistas llevaran a escena la historia de dos jovenes policias, "
	                    + "precio=$120</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (2).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Adonde van los corazones rotos" + "\"" + ">[/url]"
	                    + "<p>A donde van los corazones rotos"
	                    + "La situacion se desarrolla en la playa que rodea al Faro. Son las primeras horas de la tarde. El cielo se nublo, hay viento. Poca gente alrededor. "
	                    + "Solo un grupo que a lo lejos juega un partido de futbol. "
	                    + "precio=$90</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (3).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Buena gente" + "\"" + ">[/url]"
	                    + "<p>Buena gente"
	                    + "La obra que indaga sobre los diferentes caminos por los que la vida puede conducirte, propone revelar la vida de Margarita (Mercedes Moran),"
	                    + "una mujer muy de barrio. "
	                    + "precio=$200</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (4).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Bien de tango" + "\"" + ">[/url]"
	                    + "<p>Bien de tango"
	                    + "Un magico viaje a los anos dorados del tango. 20 artistas en escena recorren todos los estilos del genero en refinada fusion de baile,"
	                    + "sobre un exquisito trabajo coreografico .Orquesta en vivo. "
	                    + "A traves de una propuesta escenica integral, el tango se viste de gala en este musical pleno de emocion y de mistica tanguera."
	                    + "20 cultores del mas puro tango transitan sobre el escenario el legendario camino del 2x4 abrazando cada estilo y cada epoca. "
	                    + "Un magico viaje a los anos dorados del tango."
	                    + "precio=$45</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (5).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Criticonas" + "\"" + ">[/url]"
	                    + "<p>Criticonas"
	                    + "Criticonas es, esencialmente, un show de monologos de humor-stand up. Surgio como una casualidad, el 8 de marzo, "
	                    + "en el marco del Dia Internacional de la Mujer: los cuatro comediantes que integran el elenco decidieron hacer una funcion homenaje,"
	                    + " adaptaron su material y se vistieron de mujeres. El espectaculo, entre explosivo y bizarro, "
	                    + "causo tal impacto en el publico que fue ganando un espacio fijo en la grilla teatral de los domingos a la noche"
	                    + "precio=$95</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (6).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Campa/Pichot" + "\"" + ">[/url]"
	                    + "<p>Campa/Pichot"
	                    + "Campa/Pichot renueva el joven genero del stand up en Argentina, con la combinacion explosiva de los talentos de Ezequiel Campa y Malena Pichot sobre el escenario."
	                    + "Luego de participar en varios de los espectaculos mas importantes del genero, "
	                    + "Ezequiel Campa y Malena Pichot se han reunido para montar este show en el que recorren lo mejor sus amplios repertorios humoristicos, "
	                    + "con textos originales creados por ellos mismos."
	                    + "Ezequiel Campa, con varios anos de comediante, una extensa carrera en cine, teatro y TV y un singular estilo para llevar a cabo sus originales monologos,"
	                    + " repletos de energia y observaciones milimetricas."
	                    + "precio=$100</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (7).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Cachafaz" + "\"" + ">[/url]"
	                    + "<p>cachafaz"
	                    + "Copi, con su mirada descarada, ironica y arriesgada, nos enfrenta a esta historia de guapos de conventillo. Cachafaz y La Raulito, "
	                    + "entre el hambre y la indecencia, entre policias y vecinos, son los heroes desvergonzados de esta, su ultima payada mistonga morocote.[br /]"
	                    + "Cachafaz nos toma, nos mezcla, nos deglute y nos vomita. Nos hace ver lo que no podemos, o no queremos ver al transitar la experiencia de este conventillo en ruinas."
	                    + "precio=$85</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (.jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Distintos" + "\"" + ">[/url]"
	                    + "<p>Distontos"
	                    + "Puro stand up en una sala de cafe concert en el corazon del Paseo La Plaza. "
	                    + "Tres de los mejores comediantes de Buenos Aires: Guillermo Selci, Luciano Mellera y Juan Barraza, "
	                    + "se unieron para hacer este espectaculo con tres estilos distintos."
	                    + "precio=$75</strong>"
	                    + "<center><IMG SRC=" + "\"" + "t_15861ch.jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "El brillo extraviado" + "\"" + ">[/url]"
	                    + "<p>El brillo extraviado"
	                    + "Perro y Chiqui son dos amigos inseparables capaces de dar la vida por el otro.[br /]"
	                    + "Perro hereda un terrenoen las afueras de la ciudad, muy cerca del mar. El lugar ideal para que ellos, al fin,"
	                    + " puedan hacer lo que quieran,sin las miradas ni los juicios de los demas. Pero un descubrimiento irrumpira ese halo"
	                    + " de tranquilidad que Perro y Chiqui fuerona cultivar. En ese paramo, barnizado de sol y mar, el dolor los ha intrusado. Un grito de justicia se apoderara de ellos."
	                    + "Y, tal vez, sus fantasias de ser superheroes se vuelvan realidad. Dos mundos paralelos se vuelven a juntar. Cuando termina el universo ¿Que hay?"
	                    + "precio=$90</strong>"
	                    + "<center><IMG SRC=" + "\"" + "El Brillo Extraviado - Web Head - 01.jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "La cabra" + "\"" + ">[/url]"
	                    + "<p> la cabrauna obra de Edward Albee, que atraviesa cuestiones centrales en la vida de todos: el amor, los celos, los suenos, el tiempo, los valores. "
	                    + "La comedia y el drama son las formas elegidas para poder guiar esta historia conmovedora, familiar y extraordinaria.[br /]"
	                    + "Charlie acaba de ganar el premio Pritzker, su vida junto a su esposa Julia, y su hijo Willy, parece estar en armonia. "
	                    + "Sin embargo, Charlie oculta, por primera vez, un amor; y eso lo perturba. "
	                    + "La naturaleza de ese amor los enfrentara a todos a algo inesperado: una crisis de sus vidas como nunca imaginaron."
	                    + "precio=$145</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (10).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
	                    + "[br /]"
	                    + "<strong><TABLE BORDER="+ "\"" +"2"+ "\"" +" bgcolor="+ "\"" +"#ffffff"+ "\"" +" >"
	                    + "<TR><TD>"
	                    + "<a name=" + "\"" + "Entre dos mundos" + "\"" + ">[/url]"
	                    + "<p> Entre dos mundos"
	                    + "La vida parece sonreirle al joven escultor. No posee riquezas pero si talento, esperanzas grandes, y una mujer a la que ama, su doncella. "
	                    + "En su camino aparecera la serpiente, quien querra convencerlos de que intentan vivir una utopia y que la realidad, regida por un mundo materialista, "
	                    + "exigira tarde o temprano que sucumban ante ella.[br /]"
	                    + "Vulnerable e inseguro, el escultor decidira abandonar su verdadera vocacion. "
	                    + "El sistema lo espera, una vez dentro, sus anhelos podrian distorsionarse"
	                    + "precio=$110</strong>"
	                    + "<center><IMG SRC=" + "\"" + "images (9).jpg" + "\"" + "></center>"
	                    + "</TD></TABLE>"
                    + "</body>"
            + "</html>";

            oos.writeUTF(h);
            oos.close();
            fos.close();
            System.out.println("Fichero html generado");
        } catch (Exception e1) {
            System.out.println("Mensaje error: " + e1.getMessage());
        }
	
}
}
